### ISSUE TITLE
Repo doesn't have binaries for 3.0.0

### ISSUE THREAD

**Issue by unoexperto** [NewMotion/akka-rabbitmq#38]
Looks like binaries are missing at http://nexus.thenewmotion.com/content/groups/public/com/thenewmotion/akka/akka-rabbitmq_2.11/3.0.0/

Have they been moved  ?

**Comment by fedgehog** [comment]
Hello, @unoexperto.
This version available at maven central, see http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.thenewmotion%22%20AND%20a%3A%22akka-rabbitmq_2.11%22

**Comment by unoexperto** [comment]
Thanks!
