### ISSUE TITLE
akka-rabbitmq-2.3 jars are missing from the newmotion Nexus

### ISSUE THREAD

**Issue by JanGe** [NewMotion/akka-rabbitmq#53]
We're currently having issues with some of our builds that still rely on fairly old versions of `akka-rabbitmq`
```
sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.3: not found
```
even though we have the resolver configured to use the newmotion Nexus in our `build.sbt`s:
```
resolvers += "New Motion Repository" at "http://nexus.thenewmotion.com/content/groups/public/"
```

It looks like the jars are missing from the repository, but the folder structure is still intact:
<img width="987" alt="Screenshot 2019-04-08 at 11 14 15 AM" src="https://user-images.githubusercontent.com/1636981/55696469-a6ae3000-59ef-11e9-87b6-9ca9c05f70c2.png">
https://nexus.thenewmotion.com/content/groups/public/com.thenewmotion.akka/akka-rabbitmq_2.11/2.3/jars/

**Comment by poohsen** [comment]
not sure what happened there but if you upgrade to 3.0.0 you should be fine. (you will have to change the group id  `com.thenewmotion` in that case: ` "com.thenewmotion" %% "akka-rabbitmq" % "3.0.0"`)

**Comment by redkhalil** [comment]
I have a project that has an indirect dependency on akka-rabbitmq-2.3 (via spingo rabbitmq library). Is there any way we can get hold of the binaries and pom files for akka-rabbitmq-2.3 for scala 2.11?

**Comment by poohsen** [comment]
no, sorry.
